### PR TITLE
103 change andaconda to conda-forge

### LINKED ISSUE #103: switch to conda-forge due to license issue with anaconda

### PR DESCRIPTION
**Pull request by emlynjdavies**
Fixed #103

### CODE REVIEW

**Comment by emlynjdavies** [comment]
Traceback (most recent call last):
  File "C:\Users\emlynd\PySilCam\pysilcam\silcamgui\silcamgui.py", line 5, in <module>
    from PyQt5.QtWidgets import (QMainWindow, QApplication, QDialog, QVBoxLayout, QFileDialog, QMessageBox)
ImportError: DLL load failed while importing QtWidgets: The specified module could not be found.

when trying to launch the GUI on windows.

I do not get this error from master.

**Comment by WillRNaylor** [comment]
@emlynjdavies, I got a similar-but-different error to your comment above, but see that conda-forge and anaconda have slightly different latest versions of PyQt. This newer versioned worked for me (worked for me = the gui succesfully launched and processed images).

**Comment by emlynjdavies** [comment]
@WillRNaylor OK. Cool. I can give this a try on my machine again.

**Comment by emlynjdavies** [comment]
Main GUI works and processed a few images. The interactive summary crashed on loading (not sure if this is related):

QWidget::setLayout: Attempting to set QLayout "" on InteractivePlotter "", which already has a layout
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\emlynd\Anaconda3\envs\silcam\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\emlynd\Anaconda3\envs\silcam\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\emlynd\pysilcam\pysilcam\silcamgui\interactive_summary.py", line 648, in main
    window = InteractivePlotter()
  File "c:\users\emlynd\pysilcam\pysilcam\silcamgui\interactive_summary.py", line 107, in __init__
    self.statusBar.showMessage('Hello. Load a -STATS file to start', 1e12)
OverflowError: argument 2 overflowed: value must be in the range -2147483648 to 2147483647

**Comment by emlynjdavies** [comment]
This seems to work OK on my end now. Found another bug (#110 ), but think this is unrelated to this PR

**Comment by emlynjdavies** [comment]
error on linux when trying to run silcam process:

Intel MKL FATAL ERROR: Cannot load /home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/scipy/linalg/../../../../libmkl_rt.so.

**Comment by emlynjdavies** [comment]
@WillRNaylor 

Is this a related error:

Traceback (most recent call last):
  File "/home/emlynd/miniconda3/envs/silcam/bin/silcam", line 33, in <module>
    sys.exit(load_entry_point('PySilCam', 'console_scripts', 'silcam')())
  File "/home/emlynd/PySilCam/pysilcam/__main__.py", line 97, in silcam
    silcam_process(args['<configfile>'], datapath, multiProcess=multiProcess, realtime=False,
  File "/home/emlynd/PySilCam/pysilcam/__main__.py", line 337, in silcam_process
    collector(inputQueue, outputQueue, datafilename, proc_list, False,
  File "/home/emlynd/PySilCam/pysilcam/__main__.py", line 600, in collector
    write_stats(datafilename, task)
  File "/home/emlynd/PySilCam/pysilcam/process.py", line 534, in write_stats
    stats_all.to_hdf(fh, 'ParticleStats/stats', append=True, format='t', data_columns=True)
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/core/generic.py", line 2434, in to_hdf
    pytables.to_hdf(
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/io/pytables.py", line 270, in to_hdf
    f(store)
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/io/pytables.py", line 239, in <lambda>
    f = lambda store: store.append(
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/io/pytables.py", line 1255, in append
    self._write_to_group(
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/io/pytables.py", line 1788, in _write_to_group
    s.write(
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/io/pytables.py", line 4232, in write
    table = self._create_axes(
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/io/pytables.py", line 3900, in _create_axes
    data_converted = _maybe_convert_for_string_atom(
  File "/home/emlynd/miniconda3/envs/silcam/lib/python3.8/site-packages/pandas/io/pytables.py", line 4920, in _maybe_convert_for_string_atom
    if eci > itemsize:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Review by WillRNaylor — APPROVED** [review]

**Pull request merged**
