### PR TITLE
Sphix GitHub action

### PR DESCRIPTION
**Pull request by nepstad**

### CODE REVIEW

**Review by tankefugl — APPROVED** [review]
No linting violations have been found in this PR.

**Review by tankefugl — APPROVED** [review]
No linting violations have been found in this PR.

**Review by tankefugl — APPROVED** [review]
No linting violations have been found in this PR.

**Comment by espenfl** [comment]
@tankefugl @nepstad I get notifications when stuff happens here, so I thought I would just chime in a bit. You might already know it, but mention it anyway for reference. You can enable `pre-commit` (`pre-commit install`) hooks and use an `rst` linter to check linting for Sphinx. We do it like this (plenty of other config templates online if you want to check it out): https://github.com/aiida-vasp/aiida-vasp/blob/develop/.pre-commit-config.yaml. and https://github.com/aiidateam/aiida-core/blob/develop/.pre-commit-config.yaml You already check the linting in the GA, which is nice. In this way it would also be checked before you can finalize a commit.

**Comment by emlynjdavies** [comment]
solved by https://github.com/SINTEF/PySilCam/pull/109

**Pull request closed without merging**
